# Full column list per table, matches models.py exactly
class TableSchemas:

    RENTAL_PROPERTY_COLUMNS = [
        ("id", "STRING"),
        ("amenities", "ARRAY<STRING>"),
        ("themes", "ARRAY<STRING>"),
        ("amenity_categories", "ARRAY<STRING>"),
        ("activities", "ARRAY<STRING>"),
        ("activity_categories", "ARRAY<STRING>"),
        ("archived", "ARRAY<STRING>"),
        ("bathroom_count", "INT"),
        ("bedroom_count", "INT"),
        ("bedrooms", "ARRAY<INT>"),
        ("brand_id", "INT"),
        ("policy", "STRING"),
        ("check_in", "STRING"),
        ("check_out", "STRING"),
        ("zip_code", "STRING"),
        ("city", "STRING"),
        ("state", "STRING"),
        ("state_abbr", "STRING"),
        ("country", "STRING"),
        ("country_code", "STRING"),
        ("display", "STRING"),
        ("location_id", "STRING"),
        ("location_walk_scores", "STRING"),
        ("partner_location_id", "STRING"),
        ("location_assign_retry", "INT"),
        ("parent_path", "ARRAY<STRING>"),
        ("partner_country_code", "STRING"),
        ("partner_location", "STRING"),
        ("categories", "STRING"),
        ("feature_image", "STRING"),
        ("s3_feature_image", "STRING"),
        ("feed", "INT"),
        ("feed_provider_id", "STRING"),
        ("quality_score_general", "INT"),
        ("feed_provider_url", "STRING"),
        ("languages", "ARRAY<STRING>"),
        ("latlon", "STRING"),
        ("geography_latlon", "STRING"),
        ("max_occupancy", "INT"),
        ("min_stay", "INT"),
        ("minimum_confidence", "DOUBLE"),
        ("conversion_value", "DOUBLE"),
        ("conversions", "INT"),
        ("sessions", "INT"),
        ("property_score", "DOUBLE"),
        ("ml_property_score", "DOUBLE"),
        ("number_of_review", "INT"),
        ("occupancy", "INT"),
        ("online_ticket", "BOOLEAN"),
        ("event_duration", "STRING"),
        ("supported_languages", "STRING"),
        ("owner_id", "STRING"),
        ("booking_id", "STRING"),
        ("vrbo_id", "STRING"),
        ("hcom_id", "STRING"),
        ("airbnb_id", "STRING"),
        ("hometogo_id", "STRING"),
        ("kayak_id", "INT"),
        ("expedia_id", "STRING"),
        ("hotelplanner_id", "STRING"),
        ("vio_id", "STRING"),
        ("trip_id", "STRING"),
        ("license_number", "STRING"),
        ("listing_source_site", "STRING"),
        ("property_name", "STRING"),
        ("property_type", "STRING"),
        ("property_type_categories", "ARRAY<STRING>"),
        ("property_type_category", "STRING"),
        ("review_score_general", "DECIMAL(5,2)"),
        ("review_score", "DOUBLE"),
        ("review_scores", "STRING"),
        ("feed_provider_quality_score", "DOUBLE"),
        ("room_size_sqft", "DOUBLE"),
        ("room_type", "STRING"),
        ("star_rating", "DOUBLE"),
        ("unit_number", "INT"),
        ("currency", "STRING"),
        ("usd_price", "DOUBLE"),
        ("price_category", "STRING"),
        ("images", "ARRAY<STRING>"),
        ("s3_images", "ARRAY<STRING>"),
        ("pickleball_court_count", "INT"),
        ("golf_count", "INT"),
        ("uploaded_image_count", "INT"),
        ("image_quality_score", "DOUBLE"),
        ("cluster_id", "STRING"),
        ("cluster_id_json", "STRING"),
        ("cluster_pos", "STRING"),
        ("cluster_updated_at", "TIMESTAMP"),
        ("ranked_image", "STRING"),
        ("property_slug", "STRING"),
        ("complex_id", "STRING"),
        ("complex_name", "STRING"),
        ("duplicate_complex_id", "STRING"),
        ("partners_url", "STRING"),
        ("distance_from_center_miles", "STRING"),
        ("distances", "STRING"),
        ("property_manager", "STRING"),
        ("host_type", "STRING"),
        ("property_attributes", "ARRAY<STRING>"),
        ("chain_and_brand", "STRING"),
        ("commission", "STRING"),
        ("meal_plan", "ARRAY<STRING>"),
        ("duplicate_id", "STRING"),
        ("duplicate_detect_timestamp", "TIMESTAMP"),
        ("property_flags", "STRING"),
        ("has_s3_url", "BOOLEAN"),
        ("synced_in_efs", "BOOLEAN"),
        ("phone_number", "STRING"),
        ("is_active", "BOOLEAN"),
        ("published", "BOOLEAN"),
        ("is_deleted", "BOOLEAN"),
        ("is_expired", "BOOLEAN"),
        ("updated_by", "STRING"),
        ("created_at", "TIMESTAMP"),
        ("updated_at", "TIMESTAMP"),
        ("property_live_date", "TIMESTAMP"),
        ("property_modified_date", "TIMESTAMP"),
        ("property_highlights_map", "STRING"),
    ]

    PROPERTY_IMAGE_META_COLUMNS = [
        ("id", "BIGINT"),
        ("property_id", "STRING"),
        ("feed", "STRING"),
        ("url", "STRING"),
        ("path", "STRING"),
        ("label", "STRING"),
        ("captions", "STRING"),
        ("confidence", "DOUBLE"),
        ("image_quality_score", "DOUBLE"),
        ("predictions", "STRING"),
        ("width", "INT"),
        ("height", "INT"),
        ("country_code", "STRING"),
        ("s3_url", "STRING"),
        ("has_s3_url", "BOOLEAN"),
        ("is_vector_generated", "BOOLEAN"),
        ("is_deleted", "BOOLEAN"),
        ("updated_at", "TIMESTAMP"),
    ]

    PROPERTY_REVIEWS_COLUMNS = [
        ("id", "STRING"),
        ("property_id", "STRING"),
        ("feed", "STRING"),
        ("country_code", "STRING"),
        ("language_code", "STRING"),
        ("score", "DOUBLE"),
        ("summary", "STRING"),
        ("negative", "STRING"),
        ("positive", "STRING"),
        ("reviewer", "STRING"),
        ("review_date", "TIMESTAMP"),
        ("checkin_date", "TIMESTAMP"),
        ("checkout_date", "TIMESTAMP"),
        ("updated_at", "TIMESTAMP"),
    ]

    RENTAL_PROPERTY_LOCALIZE_COLUMNS = [
        ("id", "BIGINT"),
        ("property_id", "STRING"),
        ("address", "STRING"),
        ("captions", "STRING"),
        ("display", "STRING"),
        ("feature_summary", "STRING"),
        ("feed", "INT"),
        ("language", "STRING"),
        ("policies", "STRING"),
        ("property_description", "STRING"),
        ("area_description", "STRING"),
        ("property_name", "STRING"),
        ("property_type", "STRING"),
        ("room_arrangement", "STRING"),
        ("property_slug", "STRING"),
        ("country_code", "STRING"),
        ("is_translated", "BOOLEAN"),
        ("created_at", "TIMESTAMP"),
        ("updated_at", "TIMESTAMP"),
    ]

    PRICE_HISTORY_COLUMNS = [
        ("id", "BIGINT"),
        ("property_id", "STRING"),
        ("price", "STRING"),
        ("check_in", "DATE"),
        ("check_out", "DATE"),
        ("created_at", "TIMESTAMP"),
        ("feed", "STRING"),
        ("country_code", "STRING"),
    ]

    SKIP_PROPERTIES_COLUMNS = [
        ("id", "BIGINT"),
        ("property_id", "STRING"),
        ("feed", "STRING"),
        ("reason", "STRING"),
        ("location_id", "STRING"),
        ("updated_at", "TIMESTAMP"),
        ("updated_by", "STRING"),
    ]

    # Tables partitioned by country_code
    PARTITIONED_TABLES = {
        "rental_property",
        "rental_property_localize",
        "property_image_meta",
        "property_reviews",
        "price_history",
    }

    TABLE_COLUMNS = {
        "rental_property": RENTAL_PROPERTY_COLUMNS,
        "property_image_meta": PROPERTY_IMAGE_META_COLUMNS,
        "property_reviews": PROPERTY_REVIEWS_COLUMNS,
        "rental_property_localize": RENTAL_PROPERTY_LOCALIZE_COLUMNS,
        "price_history": PRICE_HISTORY_COLUMNS,
        "skip_properties": SKIP_PROPERTIES_COLUMNS,
    }

    @classmethod
    def columns_for(cls, table_name):
        return cls.TABLE_COLUMNS[table_name]

    @classmethod
    def is_partitioned(cls, table_name):
        return table_name in cls.PARTITIONED_TABLES
