services:

  db:
    image: postgis/postgis:16-3.4

    container_name: booking-postgis

    environment:
      POSTGRES_DB: booking_attraction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: booking-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile

    container_name: booking-django

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app

    ports:
      - "8000:8000"
      - "8888:8888"

    depends_on:
      - db

volumes:
  postgres_data:
  es_data: