services:

  db:
    image: postgis/postgis:16-3.4

    container_name: booking-postgis

    environment:
      POSTGRES_DB: booking_attraction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: booking-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: booking-dynamodb
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    ports:
      - "8001:8000"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: booking-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  minio:
    image: minio/minio:latest
    container_name: booking-minio

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5


  minio-init:
    image: minio/mc:latest
    container_name: booking-minio-init

    depends_on:
      minio:
        condition: service_healthy

    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing local/sitemap;
      exit 0;
      "

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile

    container_name: booking-django

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app

    ports:
      - "8000:8000"
      - "8888:8888"

    depends_on:
      - db

volumes:
  postgres_data:
  es_data:
  qdrant_data:
  minio_data: