# Generated by Django 5.2.16 on 2026-07-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDuplicateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(db_index=True, max_length=20)),
                ('duplicate_id', models.CharField(db_index=True, max_length=20)),
                ('score', models.FloatField()),
            ],
            options={
                'verbose_name': 'Property Duplicate',
                'verbose_name_plural': 'Property Duplicates',
                'db_table': 'property_duplicate_groups',
                'indexes': [models.Index(fields=['property_id'], name='property_du_propert_97df9f_idx'), models.Index(fields=['duplicate_id'], name='property_du_duplica_6d1b1c_idx')],
                'constraints': [models.UniqueConstraint(fields=('property_id', 'duplicate_id'), name='unique_property_duplicate_pair')],
            },
        ),
    ]
