# Generated by Django 6.0.7 on 2026-07-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_review_count', models.IntegerField(blank=True, null=True)),
                ('categories', models.JSONField(default=list)),
                ('badges', models.JSONField(default=list)),
                ('booking_web_url', models.TextField(blank=True, null=True)),
                ('booking_app_url', models.TextField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('location_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'attractions',
            },
        ),
        migrations.CreateModel(
            name='AttractionReview',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='attractions.attraction')),
            ],
            options={
                'db_table': 'attraction_reviews',
            },
        ),
        migrations.CreateModel(
            name='AttractionLocalized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized', to='attractions.attraction')),
            ],
            options={
                'db_table': 'attraction_localized',
                'constraints': [models.UniqueConstraint(fields=('attraction', 'language_code'), name='uq_localized_attraction_language')],
            },
        ),
        migrations.CreateModel(
            name='AttractionPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='attractions.attraction')),
            ],
            options={
                'db_table': 'attraction_photos',
                'constraints': [models.UniqueConstraint(fields=('attraction', 'photo_url'), name='uq_photos_attraction_url')],
            },
        ),
        migrations.CreateModel(
            name='AttractionReviewScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(max_length=255)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_scores', to='attractions.attraction')),
            ],
            options={
                'db_table': 'attraction_review_scores',
                'constraints': [models.UniqueConstraint(fields=('attraction', 'score_type'), name='uq_scores_attraction_type')],
            },
        ),
    ]
